
USE Examen_Coppel
IF OBJECT_ID('dbo.ROLES', 'U') IS NOT NULL 
  DROP TABLE dbo.ROLES; 

CREATE TABLE ROLES (
	ID INT IDENTITY(1,1) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL, 
	ESTATUS BIT NOT NULL,
	FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
	DIAS_TRABAJADOS_TURNO INT,
	HORAS_TRABAJADAS_TURNO INT,
	PAGO_POR_HORA DECIMAL(18,2),
	BONOS_POR_ENTREGA DECIMAL(18,2),
	BONOS_POR_HORA DECIMAL(18,2),
	USUARIO_MODIFICACION VARCHAR(50),
	FECHA_MODIFICACION DATETIME,

	PRIMARY KEY (ID)
)