
USE Examen_Coppel
IF OBJECT_ID('dbo.IMPUESTOS', 'U') IS NOT NULL 
  DROP TABLE dbo.IMPUESTOS; 

CREATE TABLE IMPUESTOS (
	ID INT IDENTITY(1,1) NOT NULL,
	ISR DECIMAL(18,2) NOT NULL,
	ISR_ADICIONAL DECIMAL(18,2),
	VALES_DESPENSA DECIMAL(18,2),

	PRIMARY KEY (ID)
)