
USE Examen_Coppel
IF OBJECT_ID('dbo.EMPLEADOS', 'U') IS NOT NULL 
  DROP TABLE dbo.EMPLEADOS; 

CREATE TABLE EMPLEADOS (
	ID INT IDENTITY(1,1) NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO_PATERNO VARCHAR(50) NOT NULL,
	APELLIDO_MATERNO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50),
	TELEFONO VARCHAR(10),
	SEXO CHAR(1),
	FECHA_NACIMIENTO DATE,
	ESTATUS BIT NOT NULL,
	ID_ROL INT NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID)
)