
USE Examen_Coppel
IF OBJECT_ID('dbo.MOVIMIENTOS', 'U') IS NOT NULL 
  DROP TABLE dbo.MOVIMIENTOS; 

CREATE TABLE MOVIMIENTOS (
	ID INT IDENTITY(1,1) NOT NULL, 
	ID_EMPLEADO INT NOT NULL,
	ID_ROL INT NOT NULL,
	MES_MOVIMIENTO INT NOT NULL,
	YEAR_MOVIMIENTO INT NOT NULL,
	CANTIDAD_ENTREGAS INT NOT NULL,
	FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

	PRIMARY KEY (ID),
	FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID),
	FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID)
	
)