
USE Examen_Coppel
IF OBJECT_ID('dbo.USUARIOS', 'U') IS NOT NULL 
  DROP TABLE dbo.USUARIOS; 

CREATE TABLE USUARIOS (
	ID INT IDENTITY(1,1) NOT NULL,
	USUARIO_NOMBRE VARCHAR(50) NOT NULL,
	USUARIO_PASSWORD VARCHAR(100) NOT NULL, 
	USUARIO_ESTATUS BIT NOT NULL DEFAULT 1,
	FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
	USUARIO_MODIFICACION VARCHAR(50),
	FECHA_MODIFICACION DATETIME

	PRIMARY KEY (ID)
)