

INSERT INTO ROLES 
VALUES('CHOFER', 1, GETDATE(), 6, 8, 30, 5.00, 10.00, 'JESUS.BARRIOS', GETDATE())

INSERT INTO ROLES 
VALUES('CARGADOR', 1, GETDATE(), 6, 8, 30, 5.00, 5.00, 'JESUS.BARRIOS', GETDATE())

INSERT INTO ROLES 
VALUES('AUXILIAR', 1, GETDATE(), 6, 8, 30, 5.00, 0.00, 'JESUS.BARRIOS', GETDATE())

SELECT * FROM ROLES

--DELETE FROM ROLES