
USE Examen_Coppel
IF OBJECT_ID('dbo.SP_CONSULTA_PAGO_POR_EMPLEADO_ROL_MES_ANIO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.SP_CONSULTA_PAGO_POR_EMPLEADO_ROL_MES_ANIO
GO
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		JESUS MANUEL LOPEZ BARRIOS
-- Create date: 07/05/2023
-- Description:	CONSULTA DEL PAGO POR EMPLEADO, ROL, MES Y AÑO.
-- =============================================
CREATE PROCEDURE SP_CONSULTA_PAGO_POR_EMPLEADO_ROL_MES_ANIO
	@ID_EMPLEADO INT,
	@ID_ROL INT,
	@MES INT,
	@YEAR INT
AS
BEGIN

	SET NOCOUNT ON;

	SELECT ID FROM PAGOS WHERE ID_EMPLEADO = @ID_EMPLEADO AND ID_ROL = @ID_ROL AND PAGO_DEL_MES = @MES AND PAGO_DEL_YEAR = @YEAR
END
GO