
USE Examen_Coppel
IF OBJECT_ID('dbo.SP_GUARDAR_MOVIMIENTOS', 'P') IS NOT NULL
	DROP PROCEDURE dbo.SP_GUARDAR_MOVIMIENTOS
GO
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		JESUS MANUEL LOPEZ BARRIOS
-- Create date: 07/05/2023
-- Description:	PROCEDIMIENTO PARA GUARDAR LOS MOVIMEINTOS DE LOS EMPLEADOS EN EL MES.
-- =============================================
CREATE PROCEDURE SP_GUARDAR_MOVIMIENTOS

	@ID_EMPLEADO INT,
	@ID_ROL INT,
	@MES INT,
	@YEAR INT,
	@CANTIDAD_ENTREGAS INT,
	@FECHA_REGISTRO DATETIME
AS
BEGIN

	SET NOCOUNT ON;

	BEGIN TRY
		INSERT INTO MOVIMIENTOS (ID_EMPLEADO, ID_ROL, MES_MOVIMIENTO, YEAR_MOVIMIENTO, CANTIDAD_ENTREGAS, FECHA_REGISTRO)
		VALUES (@ID_EMPLEADO, @ID_ROL, @MES, @YEAR, @CANTIDAD_ENTREGAS, @FECHA_REGISTRO)

		RETURN 1
	END TRY
	BEGIN CATCH
		RETURN 0
	END CATCH
END
GO