
USE Examen_Coppel
IF OBJECT_ID('dbo.SP_GUARDAR_EMPLEADO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.SP_GUARDAR_EMPLEADO
GO
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		JESUS MANUEL LOPEZ BARRIOS
-- Create date: 07/05/2023
-- Description:	PROCEDIMIENTO PARA GUARDAR UN EMPLEADO.
-- =============================================
CREATE PROCEDURE SP_GUARDAR_EMPLEADO

	@NOMBRE VARCHAR(50),
	@APELLIDO_PATERNO VARCHAR(50),
	@APELLIDO_MATERNO VARCHAR(50),
	@EMAIL VARCHAR(50),
	@TELEFONO VARCHAR(10),
	@SEXO CHAR(1),
	@FECHA_NACIMIENTO DATE,
	@ESTATUS BIT,
	@ID_ROL INT,
	@ID_EMPLEADO BIT
AS
BEGIN

	SET NOCOUNT ON;

	BEGIN TRY  

		IF (@ID_EMPLEADO = 0)
		BEGIN

			INSERT INTO EMPLEADOS(NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, EMAIL, TELEFONO, SEXO, FECHA_NACIMIENTO, ESTATUS, ID_ROL)
			VALUES (@NOMBRE, @APELLIDO_PATERNO, @APELLIDO_MATERNO, @Email, @TELEFONO, @SEXO, @FECHA_NACIMIENTO, @ESTATUS, @ID_ROL)

			DECLARE @ID INT = (SELECT MAX(ID) FROM EMPLEADOS)
		END
		ELSE
		BEGIN
			UPDATE EMPLEADOS
			SET 
				NOMBRE = @NOMBRE,
				APELLIDO_PATERNO = @APELLIDO_PATERNO,
				APELLIDO_MATERNO = @APELLIDO_MATERNO,
				EMAIL = @EMAIL,
				TELEFONO = @TELEFONO,
				SEXO = @SEXO,
				FECHA_NACIMIENTO = @FECHA_NACIMIENTO,
				ESTATUS = @ESTATUS,
				ID_ROL = ID_ROL
			WHERE ID = @ID_EMPLEADO

			RETURN @ID_EMPLEADO
		END

		RETURN @ID
	END TRY  
	BEGIN CATCH  
		RETURN 0
	END CATCH
END
GO